### ISSUE TITLE
Briefcase crash on allegedly duplicate forms in storage dir

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#319]
As reported by @kkrawczyk123 on Slack, she got the following error launching Briefcase:

```
Katarzynas-Mac-mini:libs katarzynakrawczyk$ java -jar ODK\ Briefcase\ v1.8.0-208-g8e2955b.jar
[AWT-EventQueue-0] INFO com.brsanthu.googleanalytics.GoogleAnalytics - Initializing Google Analytics with config=GoogleAnalyticsConfig [threadNameFormat=googleanalytics-thread-{0}, enabled=true, maxThreads=1, useHttps=true, validate=true, httpUrl=http://www.google-analytics.com/collect(35 B)
http://www.google-analytics.com/collect
, httpsUrl=https://ssl.google-analytics.com/collect(35 B)
https://ssl.google-analytics.com/collect
, userAgent=java/1.8.0_151-b12/Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/Mac OS X/10.11.6/x86_64, proxyPort=80, deriveSystemParameters=true, gatherStats=false] and defaultRequest=Request [parms={TRACKING_ID=UA-91951913-3, HIT_TYPE=pageview, PROTOCOL_VERSION=1, USER_LANGUAGE=en-US, CLIENT_ID=db65975f-4e23-46b0-a6da-2698f6e82bbd, DOCUMENT_ENCODING=UTF-8}, customDimensions={}, customMetrics={}]
[AWT-EventQueue-0] INFO org.opendatakit.briefcase.model.TerminationFuture - cancel requested: Main window closed
[AWT-EventQueue-0] INFO org.opendatakit.briefcase.model.TerminationFuture - cancel requested: Main window closed
Katarzynas-Mac-mini:libs katarzynakrawczyk$ java -jar ODK\ Briefcase\ v1.8.0-222-gbf756a6.jar
[AWT-EventQueue-0] INFO com.brsanthu.googleanalytics.GoogleAnalytics - Initializing Google Analytics with config=GoogleAnalyticsConfig [threadNameFormat=googleanalytics-thread-{0}, enabled=true, maxThreads=1, useHttps=true, validate=true, httpUrl=http://www.google-analytics.com/collect(35 B)
http://www.google-analytics.com/collect
, httpsUrl=https://ssl.google-analytics.com/collect(35 B)
https://ssl.google-analytics.com/collect
, userAgent=java/1.8.0_151-b12/Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/Mac OS X/10.11.6/x86_64, proxyPort=80, deriveSystemParameters=true, gatherStats=false] and defaultRequest=Request [parms={CLIENT_ID=ccf7e1f6-62be-42f8-8fb2-878eb1e8f9a8, TRACKING_ID=UA-91951913-3, DOCUMENT_ENCODING=UTF-8, USER_LANGUAGE=en-US, PROTOCOL_VERSION=1, HIT_TYPE=pageview}, customDimensions={}, customMetrics={}]
[AWT-EventQueue-0] ERROR org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa - failed to launch app
java.lang.IllegalStateException: Duplicate key org.opendatakit.briefcase.model.FormStatus@e1c7b2b
    at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
    at java.util.HashMap.merge(HashMap.java:1254)
    at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.opendatakit.briefcase.export.ExportForms.rebuildIndex(ExportForms.java:192)
    at org.opendatakit.briefcase.export.ExportForms.<init>(ExportForms.java:48)
    at org.opendatakit.briefcase.export.ExportForms.load(ExportForms.java:65)
    at org.opendatakit.briefcase.ui.export.ExportPanel.from(ExportPanel.java:107)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:233)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:54)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow$1.run(MainBriefcaseWindow.java:179)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
#### Software versions 
Briefcase v1.x.x, Java v1.x.x, operating system, Aggregate v1.x.x, Collect v1.x.x...

#### Problem description
Failure to launch Briefcase

#### Steps to reproduce the problem
¿? Maybe dupe forms stored in disk

#### Expected behavior
¿?

**Comment by lognaturel** [comment]
I got this as well, no clear reason why! I ended up deleting the entire Briefcase folder.

**Comment by yanokwa** [comment]
@kkrawczyk123 Do you remember how we can reproduce this?

**Comment by kkrawczyk123** [comment]
I just built an app and tried to run it by java -jar command on MacOS and didn't understand what happened as I was expecting run, so asked @ggalmazor fo help. I will try if I can reproduce that now.

**Comment by ggalmazor** [comment]
Until we know how to reproduce it, one way to go could be to zip the storage directory and attach it to this issue when it happens again.

**Comment by ggalmazor** [comment]
Closing:
- We haven't been able to compile a step list to reproduce this particular failure
- This problem has been deeply analyzed and we've already decided to solve dupe key errors by implementing a central database and using composite keys + form hashes to solve form collisions
- Fixes and improvements have been already put in place to mitigate current problems while the Database happens
