### ISSUE TITLE
Improve spacing in CLI when entering bad flag

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#424]
#### Software versions 
Briefcase v1.9

#### Steps to reproduce the problem
Common CLI mistakes result in hard to read output.

```
$ java -jar build/libs/ODK\ Briefcase\ v1.9.0-131-ga42f932.jar -x
Unrecognized option: -x
2018-03-26 20:31:24,387 [main] ERROR org.opendatakit.common.cli.Cli - Error
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -x
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:81)
	at org.opendatakit.common.cli.Cli.getCli(Cli.java:155)
	at org.opendatakit.common.cli.Cli.run(Cli.java:109)
	at org.opendatakit.briefcase.Launcher.main(Launcher.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Usage: java -jar briefcase.jar <params>

Available operations:
-c,--clear_prefs                    Clear saved preferences
-e,--export                         Export a form
```

```
$ java -jar build/libs/ODK\ Briefcase\ v1.9.0-131-ga42f932.jar -pla
2018-03-26 20:33:14,798 [main] ERROR o.o.a.p.BaseFormParserForJavaRosa - form_id and storage_directory are required
usage: java -jar briefcase.jar
 -ed,--export_directory </path/to/dir>                   Directory to
                                                         export the CSV
                                                         and media files
                                                         into (relative
                                                         path unless it
                                                         begins with / or
                                                         C:\)
```

It's really hard for a human to read these messages. I think there need to be a few improvements.

1. There should be consistent usage text. The first is title case and has a newline while the second is lower case and does not. Usage text should always have a line break before and after so it's easy to read.
1. Stack traces when you type the wrong flag seems unfriendly. I say just print the error and leave the stacktraces out of it!

**Comment by ggalmazor** [comment]
OK!
- We can make the line break at column 120, for example. How about that?
- We need to find a way to have just one launcher (the new). Maybe we can delegate on the new launcher from the old by adding the flags it needs once we detect which operation we want to launch
- I think that you're seeing the stack traces only because logback is redirecting them to stdout. We don't (shouldn't) print stack traces directly to System.err|out
