### ISSUE TITLE
Prevent error when pulling from ODK folder

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#455]
In PR #353 (pull before export), we introduced a bug when the user pulls forms from a filesystem location using the ODK folder option.

To solve the "pull before export" feature we added a `ITransferFromSourceAction.getTransferSettings()` method to the interface both `TransferFromODK` and `TransferFromServer` implement.

The override on the `TransferFromServer` implementation works as expected, because we can provide the transfer settings the user has defined for the pull from Aggregate operation but, the implementation of `TransferFromODK` throws because we can't provide those settings.

I propose we go about this following this strategy:
- [x] First, provide a quick solution that conditionally calls the method and allows for those transfer settings to be null on the `TransferSucceededEvent`

- [ ] We provide a PR with improvements on the design of those classes

    We discuss and explore options to solve an underlying design problem: those two classes should not implement a common interface, because we really need to do specific stuff when dealing with a pull from Aggregate situation, which breaks the [Liskov Substitution Principle](https://www.wikiwand.com/en/Liskov_substitution_principle) and hints us about a problem on this class hierarchy.

The related Sentry crash report is here: https://sentry.io/opendatakit/briefcase/issues/525184226/

```
RuntimeException: This class has no transfer settings
    at org.opendatakit.briefcase.util.TransferFromODK.getTransferSettings(TransferFromODK.java:350)
    at org.opendatakit.briefcase.util.TransferAction$GatherTransferRunnable.run(TransferAction.java:92)

gather transfer action failed
```

**Comment by ggalmazor** [comment]
I'm closing this one since the biggest problem has been addressed and there's only a code design issue that we can review in the future
