### ISSUE TITLE
Briefcase can't launch if storage folder is moved or deleted

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#504]
If you launch Briefcase (master) via gradle and you've moved the cache.ser file, it won't run. 

```
./gradlew clean run
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Parallel execution is an incubating feature.

> Task :compileJava
Note: /Users/yanokwa/Documents/Work/Nafundi/Code/yanokwa/odk-briefcase/src/org/opendatakit/briefcase/export/ExportEvent.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run FAILED
Failed to launch Briefcase GUI2018-06-06 10:36:55,248 [main] ERROR o.o.a.p.BaseFormParserForJavaRosa - Failed to launch GUI

java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /Users/yanokwa/Desktop/ODK Briefcase Storage/cache.ser
        at org.opendatakit.briefcase.reused.UncheckedFiles.createFile(UncheckedFiles.java:133)
        at org.opendatakit.briefcase.util.FormCache.from(FormCache.java:52)
        at java.base/java.util.Optional.map(Optional.java:254)
        at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:92)
        at org.opendatakit.briefcase.ui.MainBriefcaseWindow.launchGUI(MainBriefcaseWindow.java:79)
        at org.opendatakit.briefcase.Launcher.lambda$main$1(Launcher.java:75)
        at org.opendatakit.common.cli.Cli.lambda$run$5(Cli.java:132)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.opendatakit.common.cli.Cli.run(Cli.java:132)
        at org.opendatakit.briefcase.Launcher.main(Launcher.java:79)
Caused by: java.nio.file.NoSuchFileException: /Users/yanokwa/Desktop/ODK Briefcase Storage/cache.ser
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
        at java.base/java.nio.file.Files.createFile(Files.java:640)
        at org.opendatakit.briefcase.reused.UncheckedFiles.createFile(UncheckedFiles.java:131)
        ... 9 common frames omitted
```

**Comment by ggalmazor** [comment]
@yanokwa, I can't reproduce it. How did you move the cache file?

**Comment by ggalmazor** [comment]
Oh, maybe you moved the whole storage dir?

**Comment by ggalmazor** [comment]
What would you expect when this happens? It's failing because the saved briefcase dir points to some place in your computer that doesn't exist.

One option would be to reset it and force the user to set a storage location again.

**Comment by lognaturel** [comment]
Yes, the issue is if someone moves or deletes the entire briefcase storage folder. I do think Briefcase should still be able to launch in that case. Resetting it if not found and forcing the user to set a new one sounds good to me. Probably not a priority for this release, though? I think it's been this way for some time.

**Comment by kstufflebam** [comment]
Hey all...

So I wanted to move my ODK Briefcase install to a new folder, and now I only get this error. And I can't for the life of me figure out how to reset the settings or fix the issue at all. I deleted and re-downloaded the .jar, and that didn't seem to fix the issue, either.

Any idea how to fix this?

**Comment by lognaturel** [comment]
Sorry you're running into this, @kstufflebam! We should prioritize this one now that we do see it's a problem for real users.

I believe one thing you could do is create an empty directory named `ODK Briefcase Storage` in the folder where Briefcase is looking. That should allow you to launch and then change to the new folder.

Another thing you can do is run Briefcase in command line mode with the `-c` option to clear preferences. To do this, you will need to open a command line prompt (Windows: https://www.digitalcitizen.life/7-ways-launch-command-prompt-windows-7-windows-8, macOS: https://www.macworld.co.uk/how-to/mac-software/how-use-terminal-on-mac-3608274/). You'll then type `java -jar `. I usually then just drag and drop the Briefcase jar file into the terminal window to get its location on the hard drive. Then add the `-c` option. You should end up with something like `java -jar ~/Desktop/ODK\ Briefcase\ v1.10.1-185-g3779f8d0.jar -c`. Press enter and then try launching it again as you normally would.

**Comment by kstufflebam** [comment]
Hello @lognaturel. I ran the command line as you described, and that seems to have set it back to defaults. The GUI launched, and I can now reset the working folder.

Thanks!

**Comment by lognaturel** [comment]
Awesome, thanks for that feedback @kstufflebam!

**Comment by yanokwa** [comment]
@kstufflebam Thanks for your comments on this issue. We've update Briefcase to v1.11.1 and it has a fix for this issue. You can grab the latest version at https://github.com/opendatakit/briefcase/releases/latest
