### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#546]
New in v1.11.1, likely a side effect of #542.

https://sentry.io/opendatakit/briefcase/issues/591957144/

```
SwingException: Exception handling event topic event class=org.opendatakit.briefcase.reused.StorageLocationEvent$LocationCleared, event=org.opendatakit.briefcase.reused.StorageLocationEvent$LocationCleared@f3b169, topic=null, eventObj=null
    at org.bushe.swing.event.ThreadSafeEventService.handleException(ThreadSafeEventService.java:2021)
    at org.bushe.swing.event.ThreadSafeEventService.handleException(ThreadSafeEventService.java:2009)
    at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:975)
    at org.bushe.swing.event.SwingEventService.access$001(SwingEventService.java:31)
    at org.bushe.swing.event.SwingEventService$1.run(SwingEventService.java:88)
...
(14 additional frame(s) were not displayed)

RuntimeException: InvocationTargetException when invoking annotated method from EventService publication.  Event class:class org.opendatakit.briefcase.reused.StorageLocationEvent$LocationCleared, Event:org.opendatakit.briefcase.reused.StorageLocationEvent$LocationCleared@f3b169, subscriber:org.opendatakit.briefcase.ui.MainBriefcaseWindow@844616, subscription Method=public void org.opendatakit.briefcase.ui.MainBriefcaseWindow.onFormStatusEvent(org.opendatakit.briefcase.reused.StorageLocationEvent$LocationCleared)
    at org.bushe.swing.event.annotation.BaseProxySubscriber.onEvent(BaseProxySubscriber.java:74)
    at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
    at org.bushe.swing.event.SwingEventService.access$001(SwingEventService.java:31)
    at org.bushe.swing.event.SwingEventService$1.run(SwingEventService.java:88)
    at java.awt.event.InvocationEvent.dispatch
...
(13 additional frame(s) were not displayed)

InvocationTargetException: None
    at sun.reflect.NativeMethodAccessorImpl.invoke0
    at sun.reflect.NativeMethodAccessorImpl.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke
    at java.lang.reflect.Method.invoke
    at org.bushe.swing.event.annotation.BaseProxySubscriber.onEvent(BaseProxySubscriber.java:69)
...
(17 additional frame(s) were not displayed)

NullPointerException: None
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.lockUI(MainBriefcaseWindow.java:154)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.onFormStatusEvent(MainBriefcaseWindow.java:199)
...
(19 additional frame(s) were not displayed)

Exception thrown by;EventService subscriber:BaseProxySubscriber{subscription=class org.opendatakit.briefcase.reused.StorageLocationEvent$LocationClearedveto=falserealSubscriber=org.opendatakit.briefcase.ui.MainBriefcaseWindow@844616, subscriptionMethod=public void org.opendatakit.briefcase.ui.MainBriefcaseWindow.onFormStatusEvent(org.opendatakit.briefcase.reused.StorageLocationEvent$LocationCleared), referenceStrength=WEAK, eventService=org.bushe.swing.event.SwingEventService@1d0a9ef}.  Subscriber class:class org.bushe.swing.event.annotation.BaseProxySubscriber
```

**Comment by lognaturel** [comment]
@kstufflebam Any chance you updated and saw a crash?

I'm not totally sure whether this is user-facing or not. Seems the `tabbedPane` can be `null`?

**Comment by kstufflebam** [comment]
I did update, and everything finally actually worked for me. I didn't see
the error you mentioned.

**Comment by lognaturel** [comment]
Awesome, thanks @kstufflebam!!

**Comment by ggalmazor** [comment]
This can happen when the storage dir is not anymore at the saved location and, due to the weird threading implementation in Swing and the EventBus, an event gets through faster than the 20-some lines between the `appPreferences.unsetStorageDir();` and the `tabbedPane = new JTabbedPane(JTabbedPane.TOP);` lines in the `MainBriefcaseWindow` constructor.

To avoid that error, we can initialize event subscribers at the end of the constructor. I'll prepare a fix with that.

**Comment by lognaturel** [comment]
Ahh, interesting. And do you think it actually causes a user-visible crash?

**Comment by ggalmazor** [comment]
It doesn't look like it, but I can't be sure. This is also really hard to reproduce...

**Comment by ggalmazor** [comment]
Sentry issue: [BRIEFCASE-AQ](https://sentry.io/opendatakit/briefcase/issues/591928410/)

**Comment by ggalmazor** [comment]
Sentry issue: [BRIEFCASE-4D](https://sentry.io/opendatakit/briefcase/issues/551428941/)
