### ISSUE TITLE
Ignore hidden folders while updating the Form Cache

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#551]
https://sentry.io/opendatakit/briefcase/issues/580431067/

```
FileNotFoundException: /Users/nmcp/Documents/MutasaData/ODK Briefcase Storage/forms/.DS_Store/.DS_Store.xml (Not a directory)
    at org.opendatakit.briefcase.util.FileSystemUtils.getMd5Hash(FileSystemUtils.java:344)
    at org.opendatakit.briefcase.util.FormCache.lambda$null$1(FormCache.java:115)
    at org.opendatakit.briefcase.util.FormCache.lambda$update$2(FormCache.java:112)
    at org.opendatakit.briefcase.util.FormCache.update(FormCache.java:110)
    at org.opendatakit.briefcase.util.FormCache.onPullSuccess(FormCache.java:145)
...
(32 additional frame(s) were not displayed)

No File
```

**Comment by ggalmazor** [comment]
Sentry issue: [BRIEFCASE-9A](https://sentry.io/opendatakit/briefcase/issues/579177659/)
