### ISSUE TITLE
Investigate why so much FormNotFoundException reports

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#555]
https://sentry.io/opendatakit/briefcase/issues/523231054/

```
FormNotFoundException: Form with formId ~redacted~ not found
    at org.opendatakit.briefcase.operations.PullFormFromAggregate.pullFormFromAggregate(PullFormFromAggregate.java:67)
    at org.opendatakit.briefcase.ui.BriefcaseCLI.run(BriefcaseCLI.java:69)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.main(MainBriefcaseWindow.java:182)
    at org.opendatakit.briefcase.Launcher.lambda$main$1(Launcher.java:72)
    at org.opendatakit.common.cli.Cli.run(Cli.java:125)
...
(7 additional frame(s) were not displayed)

Error
```

**Comment by yanokwa** [comment]
To be clear, this isn't necessarily bad and we shouldn't send this to Sentry.

**Comment by ggalmazor** [comment]
Agreed. I'm going to close this issue and we can reopen it if this pops up again after #564
