### ISSUE TITLE
Investigate why so many Duplicate keys while rebuilding indexes

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#556]
https://sentry.io/opendatakit/briefcase/issues/512538494/

```
IllegalStateException: Duplicate key org.opendatakit.briefcase.model.FormStatus@5de5e95
    at org.opendatakit.briefcase.push.PushForms.rebuildIndex(PushForms.java:91)
    at org.opendatakit.briefcase.push.PushForms.<init>(PushForms.java:35)
    at org.opendatakit.briefcase.ui.push.PushPanel.from(PushPanel.java:104)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:122)
    at org.opendatakit.briefcase.ui.MainBriefcaseWindow.launchGUI(MainBriefcaseWindow.java:81)
...
(20 additional frame(s) were not displayed)

Failed to launch GUI
```

**Comment by ggalmazor** [comment]
Closing since this has been already analyzed and we have agreed on implementing a central database to solve the indexing of forms
