### ISSUE TITLE
Avoid deprecated JavaRosa API

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#559]
Failed to redirect javarosa output
https://sentry.io/opendatakit/briefcase/issues/568703605/

```
Stacktrace (most recent call first):

    at org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.redirectOutput(BaseFormParserForJavaRosa.java:132)
    at org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.initializeJavaRosa(BaseFormParserForJavaRosa.java:117)
    at org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.<init>(BaseFormParserForJavaRosa.java:476)
    at org.opendatakit.briefcase.util.JavaRosaParserWrapper.<init>(JavaRosaParserWrapper.java:20)
    at org.opendatakit.briefcase.model.OdkCollectFormDefinition.<init>(OdkCollectFormDefinition.java:63)
    at org.opendatakit.briefcase.util.FileSystemUtils.getODKFormList(FileSystemUtils.java:166)
    at org.opendatakit.briefcase.ui.PullTransferPanel.updateFormStatuses(PullTransferPanel.java:379)
    at org.opendatakit.briefcase.ui.PullTransferPanel$OriginActionListener.actionPerformed(PullTransferPanel.java:177)

Failed to redirect javarosa output
```

**Comment by ggalmazor** [comment]
Closing because this code doesn't exist anymore.
