### ISSUE TITLE
Ensure prefs don't exceed max key length

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#583]
https://sentry.io/opendatakit/briefcase/issues/610057806/

```
IllegalArgumentException: Key too long: ~redacted~_startDate
    at org.opendatakit.briefcase.model.BriefcasePreferences.put(BriefcasePreferences.java:124)
    at org.opendatakit.briefcase.model.BriefcasePreferences.putAll(BriefcasePreferences.java:135)
    at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$updatePreferences$7(ExportPanel.java:134)
    at org.opendatakit.briefcase.ui.export.ExportPanel.updatePreferences(ExportPanel.java:133)
    at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$new$2(ExportPanel.java:82)
...
(48 additional frame(s) were not displayed)

Key too long: ~redacted~_startDate
```

**Comment by ggalmazor** [comment]
It turns out this is just a warning and doesn't crash Briefcase. I'm closing this one for a couple of reasons:
- We can't really solve the issue until we implement a database for holding saved prefs.
- PR #564 takes care of this error, which won't reach Sentry
