### ISSUE TITLE
Export Data fails

### ISSUE THREAD

**Issue by s13g3lb4um** [opendatakit/briefcase#680]
#### Software versions 
Briefcase v1.12.2, openjdk version "1.8.0_192", Manjaro 18.0, Aggregate v1.6.1, Collect v1.17.2

#### Problem description
When I try to export data, the next error occur:

```
2018-11-14 18:21:42,456 [Thread-10] ERROR o.o.briefcase.ui.export.ExportPanel - Error while exporting forms
java.lang.RuntimeException: Error evaluating field 'cargo': The problem was located in calculate expression for /Elecciones_Medellin_V2/GP/cargo
XPath evaluation: cannot handle function 'pulldata'
	at org.javarosa.core.model.LatestDagBase.evaluateTriggerable(LatestDagBase.java:139)
	at org.javarosa.core.model.LatestDagBase.doEvaluateTriggerables(LatestDagBase.java:63)
	at org.javarosa.core.model.Safe2014DagImpl.evaluateTriggerables(Safe2014DagImpl.java:366)
	at org.javarosa.core.model.Safe2014DagImpl.initializeTriggerables(Safe2014DagImpl.java:452)
	at org.javarosa.core.model.Safe2014DagImpl.initializeTriggerables(Safe2014DagImpl.java:430)
	at org.javarosa.core.model.FormDef.initializeTriggerables(FormDef.java:679)
	at org.javarosa.core.model.FormDef.initialize(FormDef.java:1232)
	at org.opendatakit.briefcase.export.FormDefinition.lambda$getFormControls$3(FormDefinition.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.opendatakit.briefcase.export.FormDefinition.getFormControls(FormDefinition.java:128)
	at org.opendatakit.briefcase.export.FormDefinition.from(FormDefinition.java:111)
	at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$9(ExportPanel.java:201)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.opendatakit.briefcase.ui.export.ExportPanel.export(ExportPanel.java:188)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.javarosa.xpath.XPathUnhandledException: The problem was located in calculate expression for /Elecciones_Medellin_V2/GP/cargo
XPath evaluation: cannot handle function 'pulldata'
	at org.javarosa.xpath.expr.XPathFuncExpr.eval(XPathFuncExpr.java:444)
	at org.javarosa.xpath.XPathConditional.evalRaw(XPathConditional.java:71)
	at org.javarosa.core.model.condition.Triggerable.evalRaw(Triggerable.java:219)
	at org.javarosa.core.model.condition.Recalculate.eval(Recalculate.java:63)
	at org.javarosa.core.model.condition.Triggerable.apply(Triggerable.java:152)
	at org.javarosa.core.model.LatestDagBase.evaluateTriggerable(LatestDagBase.java:125)
	... 78 common frames omitted
```

#### Steps to reproduce the problem
1. Connect to Aggregate server 
2. Pull Data from a form
3 go to export tab, select the form  an click on export 
#### Expected behavior
Export data without problems 

#### Other information 
the xml form definition and media data are attached 
[Elecciones Medellin V2.zip](https://github.com/opendatakit/briefcase/files/2583106/Elecciones.Medellin.V2.zip)

**Comment by ggalmazor** [comment]
Hi, @s13g3lb4um!

Could you try to reproduce your issue with new v1.13.0-beta.0 release, please? You can get it here: [ODK-Briefcase-v1.13.0-beta.0.jar](https://github.com/opendatakit/briefcase/releases/download/v1.13.0-beta.0/ODK-Briefcase-v1.13.0-beta.0.jar)

**Comment by s13g3lb4um** [comment]
Hi @ggalmazor  I try to reproduce  my issue in the new beta version and work correctly!!!
