### ISSUE TITLE
NPE using split select multiple + itemset

### ISSUE THREAD

**Issue by batkinson** [opendatakit/briefcase#739]
#### Software versions 
Briefcase v1.15.0, OpenJDK v1.8.0_212, Linux Mint 19.1 Tessa 

#### Problem description
It is not possible to export a form containing both static and dynamic selects when the "Split select multiples" option is enabled for some forms. The relevant log message when this is encountered follows:
~~~~
11:07:54.734 [Thread-4] ERROR org.opendatakit.briefcase.ui.export.ExportPanel - Error while exporting forms
java.lang.NullPointerException: null
	at org.opendatakit.briefcase.export.Model.getNames(Model.java:163)
	at org.opendatakit.briefcase.export.CsvSubmissionMappers.lambda$getRepeatHeader$6(CsvSubmissionMappers.java:121)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.opendatakit.briefcase.export.CsvSubmissionMappers.getRepeatHeader(CsvSubmissionMappers.java:122)
	at org.opendatakit.briefcase.export.Csv.repeat(Csv.java:75)
	at org.opendatakit.briefcase.export.Csv.lambda$mapToRepeatCsv$1(Csv.java:113)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.opendatakit.briefcase.export.Csv.getCsvs(Csv.java:51)
	at org.opendatakit.briefcase.export.ExportToCsv.export(ExportToCsv.java:87)
	at org.opendatakit.briefcase.export.ExportToCsv.export(ExportToCsv.java:58)
	at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$8(ExportPanel.java:199)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.opendatakit.briefcase.ui.export.ExportPanel.export(ExportPanel.java:184)
	at java.lang.Thread.run(Thread.java:748)
~~~~

#### Steps to reproduce the problem

1. Extract and deploy [the test form](https://github.com/opendatakit/briefcase/files/3192152/split_multiple_test.xml.zip) to an Aggregate-compatible server
2. Using Collect, download, fill out, and submit a test form (content does not matter)
4. Using Briefcase, pull all content for the test form
5. Attempt to export the form with "Split select multiples" enabled

#### Expected behavior

The export should complete and relevant export files corresponding to the single submission's data should be generated. Instead, the export terminates early, a modal error dialog is shown, and an log message with the above stack trace is displayed.

#### Other information 

It appears that the problem stems from the dynamic multiselect question using the itemset rather than an inline list of choice items. At runtime, the form will include the list of selections present in the form according to the itemset spec. However, the exporter code uses the static structure of the form (without a submission's contents) to determine the choices, which returns null. Making this null-safe addresses the issue and allows the export to finish.

**Comment by batkinson** [comment]
The offending line:

https://github.com/opendatakit/briefcase/blob/v1.15.0/src/org/opendatakit/briefcase/export/Model.java#L281

It looks like @ggalmazor already fixed this in commit b01a18ca50cd, but the reason is not apparent since it was bundle with a number of changes with a commit message of only: "Remove unused artifacts". Not ideal.

Anyway, it looks like this just needs to be released to address the issue. I'm closing this.

**Comment by batkinson** [comment]
Actually, I just re-opened so it doesn't get lost in the shuffle before people have a chance to see it. Feel free to close at will at your discretion.

**Comment by ggalmazor** [comment]
Thanks, @batkinson!
