### ISSUE TITLE
Exporting form with repeat groups freezes Briefcase

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#799]
#### Software versions 
Briefcase v1.17.x, Java v1.x.x, operating system Ubuntu, MacOS and Windows

#### Problem description
Briefcase freezes when trying to export form with audit and repeats.

#### Steps to reproduce the problem
Unpack attached zip in your sd and try to Export.

#### Expected behavior
User should be able to export form.

#### Other information 
Form that I have used: 
[audit_group_multiplicity.zip](https://github.com/opendatakit/briefcase/files/3574709/audit_group_multiplicity.zip)

Exception in thread "Thread-4" org.opendatakit.briefcase.reused.BriefcaseException
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$10(ExportPanel.java:198)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:63)
	at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:51)
	at org.opendatakit.briefcase.ui.export.ExportPanel.export(ExportPanel.java:229)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kkrawczyk123** [comment]
The issue is not connected with audits, only with repeats, I am also able to reproduce with form 
[nested_repeats.zip](https://github.com/opendatakit/briefcase/files/3575054/nested_repeats.zip)
