### ISSUE TITLE
If you have an invalid file in your Briefcase Storage Directory you throw an exception

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#81]
Run `gradle run`, and if you have an invalid file (e.g., a hidden `.DS_Store`) in your Briefcase Storage Directory Briefcase throws an exception in the log. 
```
org.opendatakit.briefcase.model.FileSystemException: Failed while reading submission xml: java.io.FileNotFoundException: /Users/yanokwa/Library/Application Support/ODK/ODK Briefcase Storage/forms/choice_filter/instances/.DS_Store/submission.xml (Not a directory)
        at org.opendatakit.briefcase.util.XmlManipulationUtils.parseXml(XmlManipulationUtils.java:290)
        at org.opendatakit.briefcase.util.ExportToCsv$1.compare(ExportToCsv.java:150)
        at org.opendatakit.briefcase.util.ExportToCsv$1.compare(ExportToCsv.java:142)
        at java.util.TimSort.binarySort(TimSort.java:296)
        at java.util.TimSort.sort(TimSort.java:221)
        at java.util.Arrays.sort(Arrays.java:1438)
        at org.opendatakit.briefcase.util.ExportToCsv.doAction(ExportToCsv.java:142)
        at org.opendatakit.briefcase.util.ExportAction$TransformFormRunnable.run(ExportAction.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Before sending a PR, please leave a comment about how you propose to fix this.

**Comment by yanokwa** [comment]
Filed at https://github.com/opendatakit/briefcase/pull/66
