### ISSUE TITLE
Impossible Decrypt and Export v1.17.2

### ISSUE THREAD

**Issue by manulpgc85** [opendatakit/briefcase#853]
#### Software versions 
Briefcase v1.17.2 Java v11.0.6, Windows 10 v1709

#### Problem description

I was using ODK Briefcase and I could made pull but when I was trying export and decrypt a form with it show me an error on Java Console..

#### Steps to reproduce the problem

I configured pull from Aggregate server, select the forms and made a pull action. After that I went to Export tab  and into the Export Configuration I put the Export Directory and PEM file location.

Finally select the form to export and click the button export.

#### Other information 

Exception in thread "Thread-6" org.opendatakit.briefcase.reused.BriefcaseException
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$10(ExportPanel.java:198)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:63)
        at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:51)
        at org.opendatakit.briefcase.ui.export.ExportPanel.export(ExportPanel.java:229)
        at java.base/java.lang.Thread.run(Thread.java:834)

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by ggalmazor** [comment]
Hi, @manulpgc85!

This doesn't apparently have to do with decryption.

The stacktrace points to a problem due to out of sync form cache and metadata files. You should be able to fix this situation by removing the cache file (`cache.ser`) at the root of your storage directory and all the `metadata.json` files in each form directory.

**Comment by Freeedim** [comment]
I have the same problem with v 1.17.3.

When clicking "Export", it just hangs without consuming resources according to the task manager.
The complete exception trace does seem to point to decryption (see attachment). It seems the parser does not recognise the attribute "length" in:
<bind nodeset="/data/base64EncryptedKey" type="string" length="2048"/>

**Comment by lognaturel** [comment]
I have gotten this same crash intermittently when exporting non-encrypted records. Closing and reopening the app has reset it. I have not yet identified a pattern.
